spring:
  application:
    name: saas-system
  profiles:
    active: druid
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30

logging:
  level:
    com.sxqibo: debug
    org.springframework.web: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mybatis-plus:
  type-aliases-package: com.sxqibo.saassystem.**.entity
  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  config-location: classpath*:mybatis-config.xml
  global-config:
    db-config:
      logic-delete-field: delete_time
#      logic-delete-value: 1
      logic-delete-value: UNIX_TIMESTAMP()
      logic-not-delete-value: 0
#    db-config:
#      id-type: assign_id
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
